CREATE DATABASE QLBH
USE QLBH

CREATE TABLE KHACHHANG 
(
	MAKH char(4) not null,
	HOTEN varchar(40),
	DCHI varchar(50),
	SODT varchar(20),
	NGSINH smalldatetime,
	DOANHSO money,
	LOAIKH tinyint,
	PRIMARY KEY (MAKH)
)

CREATE TABLE NHANVIEN 
(
	MANV char(4) not null,
	HOTEN varchar(40),
	SODT varchar(20),
	NGVL smalldatetime,
	PRIMARY KEY (MANV)
)

CREATE TABLE SANPHAM
(
	MASP char(4) not null,
	TENSP varchar(40),
	DVT varchar(40),
	NUOCSX varchar(40),
	GIA money,
	PRIMARY KEY (MASP)
)

CREATE TABLE HOADON 
(
	SOHD int not null,
	NGHD smalldatetime,
	MAKH char(4) REFERENCES KHACHHANG(MAKH),
	MANV char(4) REFERENCES NHANVIEN(MANV),
	TRIGIA money,
	PRIMARY KEY (SOHD)
)

CREATE TABLE CTHD
(
	SOHD int FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	MASP char(4) FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	SL int,
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MASP)
)

ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

-- Câu 2 --
ALTER TABLE SANPHAM ADD GHICHU varchar(20)

-- Câu 3 --
ALTER TABLE KHACHHANG ADD LOAIKH tinyint 

-- Câu 4 --
ALTER TABLE	SANPHAM ALTER COLUMN GHICHU varchar(100)

-- Câu 5 --		
ALTER TABLE SANPHAM DROP COLUMN GHICHU 

-- Câu 6 --
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH varchar(20)

-- Câu 7 --
ALTER TABLE SANPHAM ADD CONSTRAINT GT_DVT CHECK (DVT = 'CAY' OR DVT = 'HOP' OR DVT = 'CAI' OR DVT = 'QUYEN' OR DVT = 'CHUC' )
-- ALTER TABLE SANPHAM ADD CHECK (DVT = 'CAY' ... OR DVT = 'CHUC' )  "Tạo ràng buộc nhưng ko kèm theo tên

-- Câu 8 --
ALTER TABLE SANPHAM ADD CHECK (GIA >= 500 )
-- ALTER TABLE SANPHAM ADD CONSTRAINT GIA_TIEN CHECK ( GIA >= 500)

-- Câu 9 --
ALTER TABLE CTHD ADD CONSTRAINT SL_SP CHECK ( SL >= 1 )

-- Câu 10 --
ALTER TABLE KHACHHANG ADD NGDK smalldatetime
ALTER TABLE KHACHHANG ADD CHECK ( NGDK > NGSINH )