CREATE DATABASE QLHV


CREATE TABLE KHOA 
(
	MAKHOA varchar(4) PRIMARY KEY,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4),
)

CREATE TABLE MONHOC
(
	MAMH varchar(10) PRIMARY KEY,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4)
)

CREATE TABLE DIEUKIEN
(
	MAMH varchar(10) FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	MAMH_TRUOC varchar(10) FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH),
	PRIMARY KEY (MAMH, MAMH_TRUOC)
)

CREATE TABLE GIAOVIEN
(
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,		
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4)
)

CREATE TABLE LOP
(
	MALOP char(3) PRIMARY KEY,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4)
)

CREATE TABLE HOCVIEN 
(
	MAHV char(5) PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3)
)

CREATE TABLE GIANGDAY 
(
	MALOP char(3) FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
	MAMH varchar(10) FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	MAGV char(4),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	PRIMARY KEY (MALOP,MAMH)
)	

CREATE TABLE KETQUATHI 
(
	MAHV char(5) FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
	MAMH varchar(10) FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	LANTHI tinyint,
	NGTHI smalldatetime,
	DIEM numeric(4,2),
	KQUA varchar(10),
	PRIMARY KEY (MAHV,MAMH,LANTHI)
)

-- Câu 1 --
ALTER TABLE KHOA ADD CONSTRAINT FK_TRGKHOA_GV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE MONHOC ADD CONSTRAINT FK_MAKHOA_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GVKHOA_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE LOP ADD CONSTRAINT FK_TRGLOP_HV FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)
ALTER TABLE LOP ADD CONSTRAINT FK_MAGVCN_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE HOCVIEN ADD CONSTRAINT FK_HVMALOP_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
ALTER TABLE HOCVIEN ADD GHICHU varchar(40)
ALTER TABLE HOCVIEN ADD DIEMTB numeric(4,2)
ALTER TABLE HOCVIEN ADD XEPLOAI varchar(10)	

-- Câu 2 --
ALTER TABLE HOCVIEN ADD CONSTRAINT CK_MAHV CHECK ( len(MAHV) = 5 and left(MAHV,3) = MALOP and convert(int,right(MAHV,2)) > 0)

-- Câu 3. --
ALTER TABLE GIAOVIEN ADD CHECK (GIOITINH = 'Nam' or GIOITINH = 'Nu')
ALTER TABLE HOCVIEN ADD CHECK (GIOITINH = 'Nam' or GIOITINH = 'Nu')

-- Câu 4 --
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_DKDIEM CHECK ( DIEM >= 0 and DIEM <= 10)

-- Câu 5 -- 
ALTER TABLE KETQUATHI ADD CHECK( ((DIEM >= 5 and DIEM <= 10) and KQUA = 'Dat' ) or (DIEM < 5 and KQUA = 'Khong Dat'))

-- Câu 6 -- 
ALTER TABLE KETQUATHI ADD CHECK(LANTHI >= 0 and LANTHI <= 3)

-- Câu 7 -- 
ALTER TABLE GIANGDAY ADD CHECK(HOCKY >= 1 and HOCKY <= 3)

-- Câu 8 -- 
ALTER TABLE GIAOVIEN ADD CHECK(HOCVI in ('CN','KS', 'Ths','TS','PTS'))	
